// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: file_description.proto

#include "file_description.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// This is a temporary google only hack
#ifdef GOOGLE_PROTOBUF_ENFORCE_UNIQUENESS
#include "third_party/protobuf/version.h"
#endif
// @@protoc_insertion_point(includes)

namespace description {
class DescriptionDefaultTypeInternal {
 public:
  ::google::protobuf::internal::ExplicitlyConstructed<Description>
      _instance;
} _Description_default_instance_;
}  // namespace description
namespace protobuf_file_5fdescription_2eproto {
static void InitDefaultsDescription() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  {
    void* ptr = &::description::_Description_default_instance_;
    new (ptr) ::description::Description();
    ::google::protobuf::internal::OnShutdownDestroyMessage(ptr);
  }
  ::description::Description::InitAsDefaultInstance();
}

::google::protobuf::internal::SCCInfo<0> scc_info_Description =
    {{ATOMIC_VAR_INIT(::google::protobuf::internal::SCCInfoBase::kUninitialized), 0, InitDefaultsDescription}, {}};

void InitDefaults() {
  ::google::protobuf::internal::InitSCC(&scc_info_Description.base);
}

::google::protobuf::Metadata file_level_metadata[1];

const ::google::protobuf::uint32 TableStruct::offsets[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  ~0u,  // no _has_bits_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::description::Description, _internal_metadata_),
  ~0u,  // no _extensions_
  ~0u,  // no _oneof_case_
  ~0u,  // no _weak_field_map_
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::description::Description, content_hash_),
  GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(::description::Description, headers_),
};
static const ::google::protobuf::internal::MigrationSchema schemas[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
  { 0, -1, sizeof(::description::Description)},
};

static ::google::protobuf::Message const * const file_default_instances[] = {
  reinterpret_cast<const ::google::protobuf::Message*>(&::description::_Description_default_instance_),
};

void protobuf_AssignDescriptors() {
  AddDescriptors();
  AssignDescriptors(
      "file_description.proto", schemas, file_default_instances, TableStruct::offsets,
      file_level_metadata, NULL, NULL);
}

void protobuf_AssignDescriptorsOnce() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, protobuf_AssignDescriptors);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_PROTOBUF_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::internal::RegisterAllTypes(file_level_metadata, 1);
}

void AddDescriptorsImpl() {
  InitDefaults();
  static const char descriptor[] GOOGLE_PROTOBUF_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
      "\n\026file_description.proto\022\013description\"4\n"
      "\013Description\022\024\n\014content_hash\030\001 \001(\t\022\017\n\007he"
      "aders\030\002 \003(\tB\026Z\024proto/go/descriptionb\006pro"
      "to3"
  };
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
      descriptor, 123);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "file_description.proto", &protobuf_RegisterTypes);
}

void AddDescriptors() {
  static ::google::protobuf::internal::once_flag once;
  ::google::protobuf::internal::call_once(once, AddDescriptorsImpl);
}
// Force AddDescriptors() to be called at dynamic initialization time.
struct StaticDescriptorInitializer {
  StaticDescriptorInitializer() {
    AddDescriptors();
  }
} static_descriptor_initializer;
}  // namespace protobuf_file_5fdescription_2eproto
namespace description {

// ===================================================================

void Description::InitAsDefaultInstance() {
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Description::kContentHashFieldNumber;
const int Description::kHeadersFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Description::Description()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  ::google::protobuf::internal::InitSCC(
      &protobuf_file_5fdescription_2eproto::scc_info_Description.base);
  SharedCtor();
  // @@protoc_insertion_point(constructor:description.Description)
}
Description::Description(const Description& from)
  : ::google::protobuf::Message(),
      _internal_metadata_(NULL),
      headers_(from.headers_) {
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  content_hash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (from.content_hash().size() > 0) {
    content_hash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.content_hash_);
  }
  // @@protoc_insertion_point(copy_constructor:description.Description)
}

void Description::SharedCtor() {
  content_hash_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Description::~Description() {
  // @@protoc_insertion_point(destructor:description.Description)
  SharedDtor();
}

void Description::SharedDtor() {
  content_hash_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

void Description::SetCachedSize(int size) const {
  _cached_size_.Set(size);
}
const ::google::protobuf::Descriptor* Description::descriptor() {
  ::protobuf_file_5fdescription_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_file_5fdescription_2eproto::file_level_metadata[kIndexInFileMessages].descriptor;
}

const Description& Description::default_instance() {
  ::google::protobuf::internal::InitSCC(&protobuf_file_5fdescription_2eproto::scc_info_Description.base);
  return *internal_default_instance();
}


void Description::Clear() {
// @@protoc_insertion_point(message_clear_start:description.Description)
  ::google::protobuf::uint32 cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  headers_.Clear();
  content_hash_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  _internal_metadata_.Clear();
}

bool Description::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:description.Description)
  for (;;) {
    ::std::pair<::google::protobuf::uint32, bool> p = input->ReadTagWithCutoffNoLastTag(127u);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // string content_hash = 1;
      case 1: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(10u /* 10 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_content_hash()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->content_hash().data(), static_cast<int>(this->content_hash().length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "description.Description.content_hash"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      // repeated string headers = 2;
      case 2: {
        if (static_cast< ::google::protobuf::uint8>(tag) ==
            static_cast< ::google::protobuf::uint8>(18u /* 18 & 0xFF */)) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_headers()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->headers(this->headers_size() - 1).data(),
            static_cast<int>(this->headers(this->headers_size() - 1).length()),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "description.Description.headers"));
        } else {
          goto handle_unusual;
        }
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, _internal_metadata_.mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:description.Description)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:description.Description)
  return false;
#undef DO_
}

void Description::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:description.Description)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string content_hash = 1;
  if (this->content_hash().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->content_hash().data(), static_cast<int>(this->content_hash().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "description.Description.content_hash");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->content_hash(), output);
  }

  // repeated string headers = 2;
  for (int i = 0, n = this->headers_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->headers(i).data(), static_cast<int>(this->headers(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "description.Description.headers");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      2, this->headers(i), output);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), output);
  }
  // @@protoc_insertion_point(serialize_end:description.Description)
}

::google::protobuf::uint8* Description::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:description.Description)
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  // string content_hash = 1;
  if (this->content_hash().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->content_hash().data(), static_cast<int>(this->content_hash().length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "description.Description.content_hash");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->content_hash(), target);
  }

  // repeated string headers = 2;
  for (int i = 0, n = this->headers_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->headers(i).data(), static_cast<int>(this->headers(i).length()),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "description.Description.headers");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(2, this->headers(i), target);
  }

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:description.Description)
  return target;
}

size_t Description::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:description.Description)
  size_t total_size = 0;

  if ((_internal_metadata_.have_unknown_fields() &&  ::google::protobuf::internal::GetProto3PreserveUnknownsDefault())) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        (::google::protobuf::internal::GetProto3PreserveUnknownsDefault()   ? _internal_metadata_.unknown_fields()   : _internal_metadata_.default_instance()));
  }
  // repeated string headers = 2;
  total_size += 1 *
      ::google::protobuf::internal::FromIntSize(this->headers_size());
  for (int i = 0, n = this->headers_size(); i < n; i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->headers(i));
  }

  // string content_hash = 1;
  if (this->content_hash().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->content_hash());
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  SetCachedSize(cached_size);
  return total_size;
}

void Description::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:description.Description)
  GOOGLE_DCHECK_NE(&from, this);
  const Description* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Description>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:description.Description)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:description.Description)
    MergeFrom(*source);
  }
}

void Description::MergeFrom(const Description& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:description.Description)
  GOOGLE_DCHECK_NE(&from, this);
  _internal_metadata_.MergeFrom(from._internal_metadata_);
  ::google::protobuf::uint32 cached_has_bits = 0;
  (void) cached_has_bits;

  headers_.MergeFrom(from.headers_);
  if (from.content_hash().size() > 0) {

    content_hash_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.content_hash_);
  }
}

void Description::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:description.Description)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Description::CopyFrom(const Description& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:description.Description)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Description::IsInitialized() const {
  return true;
}

void Description::Swap(Description* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Description::InternalSwap(Description* other) {
  using std::swap;
  headers_.InternalSwap(CastToBase(&other->headers_));
  content_hash_.Swap(&other->content_hash_, &::google::protobuf::internal::GetEmptyStringAlreadyInited(),
    GetArenaNoVirtual());
  _internal_metadata_.Swap(&other->_internal_metadata_);
}

::google::protobuf::Metadata Description::GetMetadata() const {
  protobuf_file_5fdescription_2eproto::protobuf_AssignDescriptorsOnce();
  return ::protobuf_file_5fdescription_2eproto::file_level_metadata[kIndexInFileMessages];
}


// @@protoc_insertion_point(namespace_scope)
}  // namespace description
namespace google {
namespace protobuf {
template<> GOOGLE_PROTOBUF_ATTRIBUTE_NOINLINE ::description::Description* Arena::CreateMaybeMessage< ::description::Description >(Arena* arena) {
  return Arena::CreateInternal< ::description::Description >(arena);
}
}  // namespace protobuf
}  // namespace google

// @@protoc_insertion_point(global_scope)
